# Generated by Django 4.0.3 on 2024-01-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Publishers',
        ),
    ]
