# Generated by Django 4.2.7 on 2024-01-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsApp.books')),
            ],
            options={
                'verbose_name_plural': 'Borrowing Details',
            },
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='member',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Borrow_detail',
        ),
        migrations.AddField(
            model_name='borrowdetail',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsApp.borrow'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='books',
            field=models.ManyToManyField(related_name='borrows', through='lmsApp.BorrowDetail', to='lmsApp.books'),
        ),
    ]
