# Generated by Django 4.2.7 on 2024-01-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0004_borrowdetail_rename_member_borrow_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowdetail',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowdetail',
            name='borrow',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='BorrowDetail',
        ),
    ]
