# Generated by Django 4.2.7 on 2024-01-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_published',
            field=models.IntegerField(default=0),
        ),
    ]
