# Generated by Django 4.2.7 on 2024-01-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0008_alter_books_date_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
